// Map permission codes to modules/actions.
// Adjust to match exact strings returned by backend in `authorities`.

export const PERMISSIONS = {
  // Department
  DEPARTMENT_LIST:   'VIEW_DEPARTMENT_LIST',
  DEPARTMENT_CREATE: 'VIEW_DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'VIEW_DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE: 'VIEW_DEPARTMENT_DELETE',
  DEPARTMENT_DETAIL: 'VIEW_DEPARTMENT_DETAIL',

  // Employee
  EMPLOYEE_LIST:   'VIEW_EMPLOYEE_LIST',
  EMPLOYEE_CREATE: 'VIEW_EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE: 'VIEW_EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE: 'VIEW_EMPLOYEE_DELETE',
  EMPLOYEE_DETAIL: 'VIEW_EMPLOYEE_DETAIL',

  // User
  USER_LIST:   'VIEW_USER_LIST',
  USER_CREATE: 'VIEW_USER_CREATE',
  USER_UPDATE: 'VIEW_USER_UPDATE',
  USER_DELETE: 'VIEW_USER_DELETE',

  // Role
  ROLE_LIST:   'VIEW_ROLE_LIST',
  ROLE_CREATE: 'VIEW_ROLE_CREATE',
  ROLE_UPDATE: 'VIEW_ROLE_UPDATE',
  ROLE_DELETE: 'VIEW_ROLE_DELETE',

  // Permission
  PERMISSION_LIST:   'VIEW_PERMISSION_LIST',
  PERMISSION_CREATE: 'VIEW_PERMISSION_CREATE',
  PERMISSION_UPDATE: 'VIEW_PERMISSION_UPDATE',
  PERMISSION_DELETE: 'VIEW_PERMISSION_DELETE',

  // Contract
  CONTRACT_LIST:   'VIEW_CONTRACT_LIST',
  CONTRACT_CREATE: 'VIEW_CONTRACT_CREATE',
  CONTRACT_UPDATE: 'VIEW_CONTRACT_UPDATE',
  CONTRACT_DELETE: 'VIEW_CONTRACT_DELETE',

  // Attendance
  ATTENDANCE_LIST:   'VIEW_ATTENDANCE_LIST',
  ATTENDANCE_CREATE: 'VIEW_ATTENDANCE_CREATE',
  ATTENDANCE_UPDATE: 'VIEW_ATTENDANCE_UPDATE',
  ATTENDANCE_DELETE: 'VIEW_ATTENDANCE_DELETE',

  // Reward
  REWARD_LIST:   'VIEW_REWARD_LIST',
  REWARD_CREATE: 'VIEW_REWARD_CREATE',
  REWARD_UPDATE: 'VIEW_REWARD_UPDATE',
  REWARD_DELETE: 'VIEW_REWARD_DELETE',

  // Salary
  SALARY_LIST:   'VIEW_SALARY_LIST',
  SALARY_CREATE: 'VIEW_SALARY_CREATE',
  SALARY_UPDATE: 'VIEW_SALARY_UPDATE',
  SALARY_DELETE: 'VIEW_SALARY_DELETE',

  // Token
  TOKEN_LIST:   'VIEW_TOKEN_BLACK_LIST_LIST',
  TOKEN_DELETE: 'VIEW_TOKEN_BLACK_LIST_DELETE',
} as const
